apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: picalc-pr-
spec:
  pipelineRef:
    name: build-and-deploy-pipeline
  params:
    - name: gitUrl
      value: https://github.com/mbudano/tekton-tutorial
    - name: gitRevision
      value: beta-update
    - name: pathToYamlFile
      value: kubernetes/picalc.yaml
    - name: imageUrl
      value: us.icr.io/cloud-team/picalc
    - name: imageTag
      value: "1.0"
  serviceAccountName: pipeline-account
  workspaces:
    - name: git-source
      persistentVolumeClaim:
        claimName: picalc-source-pvc